
# ====================== GENERAL ======================
# Import additional configuration files
# import = []

# ====================== WINDOW ======================
[window]

opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Dark"

dynamic_title = true

# ====================== FONT ======================
[font]
normal.family = "Terminus"
normal.style = "Regular"
bold.family = "Terminus"
italic.family = "Terminus"
bold_italic.family = "Terminus"
size = 12.0
offset.x = 0  # For letter spacing (default: 0)
offset.y = 2  # For line spacing (default: 0)


# ====================== COLORS ======================
# GNOME Terminal Tango Dark

[colors.primary]
background = '#000000'
foreground = '#d3d7cf'

[colors.normal]
black = '#2e3436'
red = '#cc0000'
green = '#4e9a06'
yellow = '#c4a000'
blue = '#3465a4'
magenta = '#75507b'
cyan = '#06989a'
white = '#d3d7cf'

[colors.bright]
black = '#555753'
red = '#ef2929'
green = '#8ae234'
yellow = '#fce94f'
blue = '#729fcf'
magenta = '#ad7fa8'
cyan = '#34e2e2'
white = '#eeeeec'

# ====================== CURSOR ======================
[cursor]

# Cursor style
style = { shape = "Block", blinking = "Always" }  # Default: shape = "Block", blinking = "Off"

# Vi mode cursor style (falls back to the active value of the normal cursor if "None")
vi_mode_style = "None"  # Default: "None"

# Cursor blinking interval in milliseconds
blink_interval = 500  # Default: 750

# Time after which cursor stops blinking, in seconds
# blink_timeout = 5  # Default: 5

# When true, the cursor will be rendered as a hollow box when the window is not focused
unfocused_hollow = true  # Default: true

# Thickness of the cursor relative to the cell width
thickness = 0.1  # Default: 0.15
