
# ====================== GENERAL ======================
# Import additional configuration files

[general]
import = [
    "~/dot/config/alacritty/themes/dracula_plus.toml",
    # "~/dot/config/alacritty/themes/xterm.toml",
    # "~/dot/config/alacritty/themes/nord.toml",
    # "~/dot/config/alacritty/themes/night_fox.toml",



    # "~/dot/config/alacritty/themes/tomorrow_night_bright.toml",
    # "~/dot/config/alacritty/themes/midnight_haze.toml",
]

# ====================== WINDOW ======================
[window]

opacity = 0.9
padding.x = 15
padding.y = 15
decorations = "Full"
decorations_theme_variant = "Dark"

dynamic_title = true

# ====================== FONT ======================
[font]
# normal.family = "CaskaydiaCove Nerd Font"
# # normal.style = "SemiBold"
# bold.family = "CaskaydiaCove Nerd Font"
# italic.family = "CaskaydiaCove Nerd Font"
# bold_italic.family = "CaskaydiaCove Nerd Font"

normal.family = "JetBrainsMono Nerd Font"
normal.style = "Medium"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 10
offset.x = 0  # For letter spacing (default: 0)
offset.y = 0  # For line spacing (default: 0)

# ====================== COLORS ======================
# GNOME Terminal Tango Dark




# ====================== CURSOR ======================
[cursor]

# Cursor style
style = { shape = "Underline", blinking = "Always" }  # Default: shape = "Block", blinking = "Off"

# Vi mode cursor style (falls back to the active value of the normal cursor if "None")
vi_mode_style = "None"  # Default: "None"

# Cursor blinking interval in milliseconds
blink_interval = 500  # Default: 750

# Time after which cursor stops blinking, in seconds
# blink_timeout = 5  # Default: 5

# When true, the cursor will be rendered as a hollow box when the window is not focused
unfocused_hollow = false  # Default: true

# Thickness of the cursor relative to the cell width
thickness = 0.25  # Default: 0.15
