
# ====================== GENERAL ======================
# Import additional configuration files
# import = []



# ====================== WINDOW ======================
[window]

opacity = 0.8
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Dark"

# ====================== FONT ======================
[font]

normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"
size = 15.0

# ====================== COLORS ======================
[colors]
indexed_colors = [] # Default

# Transparent background colors
transparent_background_colors = false  # Default

# Draw bold text with bright colors
draw_bold_text_with_bright_colors = false  # Default

# Primary colors
[colors.primary]
foreground = "#d8d8d8"  # Default
background = "#181818"  # Default
dim_foreground = "#828482"  # Default
bright_foreground = "None"  # Default

# Cursor colors
[colors.cursor]
text = "CellBackground"  # Default
cursor = "CellForeground"  # Default

# Vi mode cursor colors
[colors.vi_mode_cursor]
text = "CellBackground"  # Default
cursor = "CellForeground"  # Default

# Search colors
[colors.search.matches]
foreground = "#181818"  # Default
background = "#ac4242"  # Default

[colors.search.focused_match]
foreground = "#181818"  # Default
background = "#f4bf75"  # Default

# Hint colors
[colors.hints.start]
foreground = "#181818"  # Default
background = "#f4bf75"  # Default

[colors.hints.end]
foreground = "#181818"  # Default
background = "#ac4242"  # Default

# Line indicator colors
[colors.line_indicator]
foreground = "None"  # Default
background = "None"  # Default

# Footer bar colors
[colors.footer_bar]
foreground = "#181818"  # Default
background = "#d8d8d8"  # Default

# Selection colors
[colors.selection]
text = "CellBackground"  # Default
background = "CellForeground"  # Default

# Normal colors
[colors.normal]
black = "#181818"  # Default
red = "#ac4242"  # Default
green = "#90a959"  # Default
yellow = "#f4bf75"  # Default
blue = "#6a9fb5"  # Default
magenta = "#aa759f"  # Default
cyan = "#75b5aa"  # Default
white = "#d8d8d8"  # Default

# Bright colors
[colors.bright]
black = "#6b6b6b"  # Default
red = "#c55555"  # Default
green = "#aac474"  # Default
yellow = "#feca88"  # Default
blue = "#82b8c8"  # Default
magenta = "#c28cb8"  # Default
cyan = "#93d3c3"  # Default
white = "#f8f8f8"  # Default

# Dim colors
[colors.dim]
black = "#0f0f0f"  # Default
red = "#712b2b"  # Default
green = "#5f6f3a"  # Default
yellow = "#a17e4d"  # Default
blue = "#456877"  # Default
magenta = "#704d68"  # Default
cyan = "#4d7770"  # Default
white = "#8e8e8e"  # Default


# ====================== CURSOR ======================
[cursor]

# Cursor style
style = { shape = "Block", blinking = "On" }  # Default: shape = "Block", blinking = "Off"

# Vi mode cursor style (falls back to the active value of the normal cursor if "None")
vi_mode_style = "None"  # Default: "None"

# Cursor blinking interval in milliseconds
blink_interval = 750  # Default: 750

# Time after which cursor stops blinking, in seconds
blink_timeout = 5  # Default: 5

# When true, the cursor will be rendered as a hollow box when the window is not focused
unfocused_hollow = true  # Default: true

# Thickness of the cursor relative to the cell width
thickness = 0.15  # Default: 0.15