
# ====================== GENERAL ======================
# Import additional configuration files
# import = []

# ====================== WINDOW ======================
[window]

opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Dark"

# ====================== FONT ======================
[font]
normal.family = "Hack"
bold.family = "Hack"
italic.family = "Hack"
bold_italic.family = "Hack"
size = 15.0

# ====================== COLORS ======================
[colors]
indexed_colors = [] # Default

# Transparent background colors
transparent_background_colors = false  # Default

# Draw bold text with bright colors
draw_bold_text_with_bright_colors = false  # Default


# ====================== CURSOR ======================
[cursor]

# Cursor style
style = { shape = "Block", blinking = "On" }  # Default: shape = "Block", blinking = "Off"

# Vi mode cursor style (falls back to the active value of the normal cursor if "None")
vi_mode_style = "None"  # Default: "None"

# Cursor blinking interval in milliseconds
blink_interval = 750  # Default: 750

# Time after which cursor stops blinking, in seconds
blink_timeout = 5  # Default: 5

# When true, the cursor will be rendered as a hollow box when the window is not focused
unfocused_hollow = true  # Default: true

# Thickness of the cursor relative to the cell width
thickness = 0.15  # Default: 0.15